//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Class_Library.CloudSVCRef1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CloudSVCSoap", Namespace="http://tempuri.org/")]
    public partial class CloudSVC : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback attemptLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback addUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback addAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback addFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkForFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFilesByUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserFreeStorageOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserTotalStorageOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCloudUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCloudUsersInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback adminUpdateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSingleUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback userUpdateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CloudSVC() {
            this.Url = global::Class_Library.Properties.Settings.Default.Class_Library_CloudSVCRef1_CloudSVC;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event attemptLoginCompletedEventHandler attemptLoginCompleted;
        
        /// <remarks/>
        public event addUserCompletedEventHandler addUserCompleted;
        
        /// <remarks/>
        public event addAdminCompletedEventHandler addAdminCompleted;
        
        /// <remarks/>
        public event addFileCompletedEventHandler addFileCompleted;
        
        /// <remarks/>
        public event checkForFileCompletedEventHandler checkForFileCompleted;
        
        /// <remarks/>
        public event getFilesByUserCompletedEventHandler getFilesByUserCompleted;
        
        /// <remarks/>
        public event getUserFreeStorageCompletedEventHandler getUserFreeStorageCompleted;
        
        /// <remarks/>
        public event getUserTotalStorageCompletedEventHandler getUserTotalStorageCompleted;
        
        /// <remarks/>
        public event getCloudUsersCompletedEventHandler getCloudUsersCompleted;
        
        /// <remarks/>
        public event getCloudUsersInfoCompletedEventHandler getCloudUsersInfoCompleted;
        
        /// <remarks/>
        public event getTransactionsCompletedEventHandler getTransactionsCompleted;
        
        /// <remarks/>
        public event adminUpdateUserCompletedEventHandler adminUpdateUserCompleted;
        
        /// <remarks/>
        public event deleteUserCompletedEventHandler deleteUserCompleted;
        
        /// <remarks/>
        public event getSingleUserInfoCompletedEventHandler getSingleUserInfoCompleted;
        
        /// <remarks/>
        public event userUpdateUserCompletedEventHandler userUpdateUserCompleted;
        
        /// <remarks/>
        public event deleteFileCompletedEventHandler deleteFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/attemptLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int attemptLogin(string[] loginInfo) {
            object[] results = this.Invoke("attemptLogin", new object[] {
                        loginInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void attemptLoginAsync(string[] loginInfo) {
            this.attemptLoginAsync(loginInfo, null);
        }
        
        /// <remarks/>
        public void attemptLoginAsync(string[] loginInfo, object userState) {
            if ((this.attemptLoginOperationCompleted == null)) {
                this.attemptLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnattemptLoginOperationCompleted);
            }
            this.InvokeAsync("attemptLogin", new object[] {
                        loginInfo}, this.attemptLoginOperationCompleted, userState);
        }
        
        private void OnattemptLoginOperationCompleted(object arg) {
            if ((this.attemptLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.attemptLoginCompleted(this, new attemptLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addUser(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("addUser", new object[] {
                        loginInfo,
                        userInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addUserAsync(string[] loginInfo, string[] userInfo) {
            this.addUserAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void addUserAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.addUserOperationCompleted == null)) {
                this.addUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddUserOperationCompleted);
            }
            this.InvokeAsync("addUser", new object[] {
                        loginInfo,
                        userInfo}, this.addUserOperationCompleted, userState);
        }
        
        private void OnaddUserOperationCompleted(object arg) {
            if ((this.addUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addUserCompleted(this, new addUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addAdmin(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("addAdmin", new object[] {
                        loginInfo,
                        userInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addAdminAsync(string[] loginInfo, string[] userInfo) {
            this.addAdminAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void addAdminAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.addAdminOperationCompleted == null)) {
                this.addAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAdminOperationCompleted);
            }
            this.InvokeAsync("addAdmin", new object[] {
                        loginInfo,
                        userInfo}, this.addAdminOperationCompleted, userState);
        }
        
        private void OnaddAdminOperationCompleted(object arg) {
            if ((this.addAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addAdminCompleted(this, new addAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int addFile(string[] loginInfo, string[] fileInfo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] fileData) {
            object[] results = this.Invoke("addFile", new object[] {
                        loginInfo,
                        fileInfo,
                        fileData});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addFileAsync(string[] loginInfo, string[] fileInfo, byte[] fileData) {
            this.addFileAsync(loginInfo, fileInfo, fileData, null);
        }
        
        /// <remarks/>
        public void addFileAsync(string[] loginInfo, string[] fileInfo, byte[] fileData, object userState) {
            if ((this.addFileOperationCompleted == null)) {
                this.addFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddFileOperationCompleted);
            }
            this.InvokeAsync("addFile", new object[] {
                        loginInfo,
                        fileInfo,
                        fileData}, this.addFileOperationCompleted, userState);
        }
        
        private void OnaddFileOperationCompleted(object arg) {
            if ((this.addFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addFileCompleted(this, new addFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkForFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet checkForFile(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("checkForFile", new object[] {
                        loginInfo,
                        userInfo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void checkForFileAsync(string[] loginInfo, string[] userInfo) {
            this.checkForFileAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void checkForFileAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.checkForFileOperationCompleted == null)) {
                this.checkForFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckForFileOperationCompleted);
            }
            this.InvokeAsync("checkForFile", new object[] {
                        loginInfo,
                        userInfo}, this.checkForFileOperationCompleted, userState);
        }
        
        private void OncheckForFileOperationCompleted(object arg) {
            if ((this.checkForFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkForFileCompleted(this, new checkForFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFilesByUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getFilesByUser(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("getFilesByUser", new object[] {
                        loginInfo,
                        userInfo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getFilesByUserAsync(string[] loginInfo, string[] userInfo) {
            this.getFilesByUserAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void getFilesByUserAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.getFilesByUserOperationCompleted == null)) {
                this.getFilesByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFilesByUserOperationCompleted);
            }
            this.InvokeAsync("getFilesByUser", new object[] {
                        loginInfo,
                        userInfo}, this.getFilesByUserOperationCompleted, userState);
        }
        
        private void OngetFilesByUserOperationCompleted(object arg) {
            if ((this.getFilesByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFilesByUserCompleted(this, new getFilesByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserFreeStorage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double getUserFreeStorage(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("getUserFreeStorage", new object[] {
                        loginInfo,
                        userInfo});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void getUserFreeStorageAsync(string[] loginInfo, string[] userInfo) {
            this.getUserFreeStorageAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void getUserFreeStorageAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.getUserFreeStorageOperationCompleted == null)) {
                this.getUserFreeStorageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserFreeStorageOperationCompleted);
            }
            this.InvokeAsync("getUserFreeStorage", new object[] {
                        loginInfo,
                        userInfo}, this.getUserFreeStorageOperationCompleted, userState);
        }
        
        private void OngetUserFreeStorageOperationCompleted(object arg) {
            if ((this.getUserFreeStorageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserFreeStorageCompleted(this, new getUserFreeStorageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserTotalStorage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double getUserTotalStorage(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("getUserTotalStorage", new object[] {
                        loginInfo,
                        userInfo});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void getUserTotalStorageAsync(string[] loginInfo, string[] userInfo) {
            this.getUserTotalStorageAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void getUserTotalStorageAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.getUserTotalStorageOperationCompleted == null)) {
                this.getUserTotalStorageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserTotalStorageOperationCompleted);
            }
            this.InvokeAsync("getUserTotalStorage", new object[] {
                        loginInfo,
                        userInfo}, this.getUserTotalStorageOperationCompleted, userState);
        }
        
        private void OngetUserTotalStorageOperationCompleted(object arg) {
            if ((this.getUserTotalStorageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserTotalStorageCompleted(this, new getUserTotalStorageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCloudUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCloudUsers(string[] loginInfo) {
            object[] results = this.Invoke("getCloudUsers", new object[] {
                        loginInfo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCloudUsersAsync(string[] loginInfo) {
            this.getCloudUsersAsync(loginInfo, null);
        }
        
        /// <remarks/>
        public void getCloudUsersAsync(string[] loginInfo, object userState) {
            if ((this.getCloudUsersOperationCompleted == null)) {
                this.getCloudUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCloudUsersOperationCompleted);
            }
            this.InvokeAsync("getCloudUsers", new object[] {
                        loginInfo}, this.getCloudUsersOperationCompleted, userState);
        }
        
        private void OngetCloudUsersOperationCompleted(object arg) {
            if ((this.getCloudUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCloudUsersCompleted(this, new getCloudUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCloudUsersInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCloudUsersInfo(string[] loginInfo) {
            object[] results = this.Invoke("getCloudUsersInfo", new object[] {
                        loginInfo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getCloudUsersInfoAsync(string[] loginInfo) {
            this.getCloudUsersInfoAsync(loginInfo, null);
        }
        
        /// <remarks/>
        public void getCloudUsersInfoAsync(string[] loginInfo, object userState) {
            if ((this.getCloudUsersInfoOperationCompleted == null)) {
                this.getCloudUsersInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCloudUsersInfoOperationCompleted);
            }
            this.InvokeAsync("getCloudUsersInfo", new object[] {
                        loginInfo}, this.getCloudUsersInfoOperationCompleted, userState);
        }
        
        private void OngetCloudUsersInfoOperationCompleted(object arg) {
            if ((this.getCloudUsersInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCloudUsersInfoCompleted(this, new getCloudUsersInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTransactions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getTransactions(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("getTransactions", new object[] {
                        loginInfo,
                        userInfo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getTransactionsAsync(string[] loginInfo, string[] userInfo) {
            this.getTransactionsAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void getTransactionsAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.getTransactionsOperationCompleted == null)) {
                this.getTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTransactionsOperationCompleted);
            }
            this.InvokeAsync("getTransactions", new object[] {
                        loginInfo,
                        userInfo}, this.getTransactionsOperationCompleted, userState);
        }
        
        private void OngetTransactionsOperationCompleted(object arg) {
            if ((this.getTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTransactionsCompleted(this, new getTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/adminUpdateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int adminUpdateUser(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("adminUpdateUser", new object[] {
                        loginInfo,
                        userInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void adminUpdateUserAsync(string[] loginInfo, string[] userInfo) {
            this.adminUpdateUserAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void adminUpdateUserAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.adminUpdateUserOperationCompleted == null)) {
                this.adminUpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnadminUpdateUserOperationCompleted);
            }
            this.InvokeAsync("adminUpdateUser", new object[] {
                        loginInfo,
                        userInfo}, this.adminUpdateUserOperationCompleted, userState);
        }
        
        private void OnadminUpdateUserOperationCompleted(object arg) {
            if ((this.adminUpdateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adminUpdateUserCompleted(this, new adminUpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteUser(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("deleteUser", new object[] {
                        loginInfo,
                        userInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteUserAsync(string[] loginInfo, string[] userInfo) {
            this.deleteUserAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void deleteUserAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.deleteUserOperationCompleted == null)) {
                this.deleteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteUserOperationCompleted);
            }
            this.InvokeAsync("deleteUser", new object[] {
                        loginInfo,
                        userInfo}, this.deleteUserOperationCompleted, userState);
        }
        
        private void OndeleteUserOperationCompleted(object arg) {
            if ((this.deleteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteUserCompleted(this, new deleteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSingleUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getSingleUserInfo(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("getSingleUserInfo", new object[] {
                        loginInfo,
                        userInfo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getSingleUserInfoAsync(string[] loginInfo, string[] userInfo) {
            this.getSingleUserInfoAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void getSingleUserInfoAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.getSingleUserInfoOperationCompleted == null)) {
                this.getSingleUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSingleUserInfoOperationCompleted);
            }
            this.InvokeAsync("getSingleUserInfo", new object[] {
                        loginInfo,
                        userInfo}, this.getSingleUserInfoOperationCompleted, userState);
        }
        
        private void OngetSingleUserInfoOperationCompleted(object arg) {
            if ((this.getSingleUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSingleUserInfoCompleted(this, new getSingleUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/userUpdateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int userUpdateUser(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("userUpdateUser", new object[] {
                        loginInfo,
                        userInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void userUpdateUserAsync(string[] loginInfo, string[] userInfo) {
            this.userUpdateUserAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void userUpdateUserAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.userUpdateUserOperationCompleted == null)) {
                this.userUpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuserUpdateUserOperationCompleted);
            }
            this.InvokeAsync("userUpdateUser", new object[] {
                        loginInfo,
                        userInfo}, this.userUpdateUserOperationCompleted, userState);
        }
        
        private void OnuserUpdateUserOperationCompleted(object arg) {
            if ((this.userUpdateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.userUpdateUserCompleted(this, new userUpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteFile(string[] loginInfo, string[] userInfo) {
            object[] results = this.Invoke("deleteFile", new object[] {
                        loginInfo,
                        userInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteFileAsync(string[] loginInfo, string[] userInfo) {
            this.deleteFileAsync(loginInfo, userInfo, null);
        }
        
        /// <remarks/>
        public void deleteFileAsync(string[] loginInfo, string[] userInfo, object userState) {
            if ((this.deleteFileOperationCompleted == null)) {
                this.deleteFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteFileOperationCompleted);
            }
            this.InvokeAsync("deleteFile", new object[] {
                        loginInfo,
                        userInfo}, this.deleteFileOperationCompleted, userState);
        }
        
        private void OndeleteFileOperationCompleted(object arg) {
            if ((this.deleteFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteFileCompleted(this, new deleteFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void attemptLoginCompletedEventHandler(object sender, attemptLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class attemptLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal attemptLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void addUserCompletedEventHandler(object sender, addUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void addAdminCompletedEventHandler(object sender, addAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void addFileCompletedEventHandler(object sender, addFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void checkForFileCompletedEventHandler(object sender, checkForFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkForFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkForFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getFilesByUserCompletedEventHandler(object sender, getFilesByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFilesByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFilesByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getUserFreeStorageCompletedEventHandler(object sender, getUserFreeStorageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserFreeStorageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserFreeStorageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getUserTotalStorageCompletedEventHandler(object sender, getUserTotalStorageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserTotalStorageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserTotalStorageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCloudUsersCompletedEventHandler(object sender, getCloudUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCloudUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCloudUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCloudUsersInfoCompletedEventHandler(object sender, getCloudUsersInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCloudUsersInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCloudUsersInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getTransactionsCompletedEventHandler(object sender, getTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void adminUpdateUserCompletedEventHandler(object sender, adminUpdateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class adminUpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal adminUpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteUserCompletedEventHandler(object sender, deleteUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getSingleUserInfoCompletedEventHandler(object sender, getSingleUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSingleUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSingleUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void userUpdateUserCompletedEventHandler(object sender, userUpdateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class userUpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal userUpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteFileCompletedEventHandler(object sender, deleteFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591